# prettier-ignore
name: Tests

on: [push]

jobs:
  all_4_versions:
    # This comment should be preserved
    name: "All 4 Versions" # These quotes should be preserved
    runs-on: 'macos-latest' # As should these
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - '11.7'
          - '12.1'
          - '12.2'
          - '12.3'

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      # A very long line that should not be modified.
      - run: echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

  last-major:
    name: Last major
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: '11.7'
        platform: ["iOS", "tvOS"]

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

  last-minor:
    name: Last minor
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: '12.1'
        platform: ["iOS", "tvOS"]

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

  beta:
    name: Beta
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: '12.3'

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

  latest:
    name: Latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: '12.2'

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

  latest-and-beta:
    name: Latest and Beta
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - '12.2'
          - '12.3'

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
