name: Pack dist/index.js

on:
  issue_comment:
    types: [created, edited]

jobs:
  pack_by_pr_comment:
    name: Pack dist/index.js
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@github-actions pack') }}
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Information
        uses: actions/github-script@v3
        id: get-pr-info
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.debug(`Getting details of PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.get-pr-info.outputs.result).head.ref }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: React to Comment
        uses: actions/github-script@v3
        with:
          script: |
            await github.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "+1"
            })

      - name: Read .node-version
        run: echo "##[set-output name=node-version;]$(cat .node-version)"
        id: node-version

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node-version.outputs.node-version }}"

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

      - run: npm run pack

      - name: Setup git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - run: git add dist/index.js

      - run: git commit -m "npm run pack"

      - run: git push origin
