name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    name: Run JS Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm install

      - run: pip3 install -r requirements.txt

      - run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  check-has-built:
    name: Check Has Been Built
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-node_v${{ steps.node-version.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-node_v${{ steps.node-version.outputs.node-version }}-

      - run: npm install

      - run: npm run pack

      - name: Check `npm run pack` was run before commit
        run: git diff --exit-code

  test-action:
    name: Test Action Run
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - run: pip3 install -r requirements.txt

      - name: Run action against test data
        uses: ./
        with:
          xcode-versions-file: ./src/__tests__/xcode-versions.yml
          xcode-search-path: ./src/__tests__/Xcodes

      - name: Validate run
        run: |
          if ! cmp --silent ./src/__tests__/workflows/input.yml ./src/__tests__/workflows/output.yml; then
            echo "Files do not match"
            echo "./src/__tests__/workflows/input.yml:"
            cat ./src/__tests__/workflows/input.yml
            echo "./src/__tests__/workflows/output.yml:"
            cat ./src/__tests__/workflows/output.yml
            exit 1
          fi

  test-python-script:
    name: Test Python Script
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - run: pip3 install -r requirements.txt

      - name: Run python script
        run: ./src/applyXcodeVersion.py jobs all_4_versions strategy matrix xcode last-major --yaml_file ./src/__tests__/workflows/input.yml

      - name: Validate run
        run: |
          if ! cmp --silent ./src/__tests__/workflows/input.yml ./src/__tests__/workflows/output.yml; then
            echo "Files do not match"
            echo "./src/__tests__/workflows/input.yml:"
            cat ./src/__tests__/workflows/input.yml
            echo "./src/__tests__/workflows/output.yml:"
            cat ./src/__tests__/workflows/output.yml
            exit 1
          fi
