name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    name: Run JS Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

      - run: pip3 install -r requirements.txt

      - run: npm run test:coverage -- --testTimeout=10000

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  check-has-built:
    name: Check Has Been Built
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

      - run: npm run pack

      - name: Check `npm run pack` was run before commit
        run: git diff --exit-code

  check-types:
    name: Check Types
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

      - run: npm run checkTypes

  test-action:
    name: Test Action Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run action against test data
        id: update-xcode-version
        uses: ./
        with:
          xcode-versions-file: ./src/__tests__/xcode-versions.yml
          xcode-search-path: ./src/__tests__/Xcodes
          xcode-version-badge-versions: "last-major, latest,beta"
          xcode-version-badge-markdown-file: ./src/__tests__/input.md
          xcode-version-badge-path: ./.github/xcode-versions-badge.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate run
        continue-on-error: true
        run: |
          if ! diff ./src/__tests__/workflows/input.yml ./src/__tests__/workflows/output-double-quotes.yml; then
            exit 1
          fi

          if ! diff ./src/__tests__/input.md ./src/__tests__/output.md; then
            exit 1
          fi

      - name: Check commit
        id: check-commit
        run: echo "##[set-output name=commit-hash;]$(git rev-parse HEAD)"

      - name: Run action against test data again
        uses: ./
        with:
          xcode-versions-file: ./src/__tests__/xcode-versions.yml
          xcode-search-path: ./src/__tests__/Xcodes
          xcode-version-badge-versions: "last-major, latest,beta"
          xcode-version-badge-path: ./.github/xcode-versions-badge.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check did not commit again
        continue-on-error: true
        run: |
          if [ "${{ steps.check-commit.outputs.commit-hash }}" != "$(git rev-parse HEAD)" ]; then
            exit 1
          fi

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

      - name: Check and close PR
        run: node ./scripts/check-and-close-pr.mjs
        env:
          PULL_REQUEST_ID: ${{ steps.update-xcode-version.outputs.pull-request-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
