name: "Tests"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    name: Run JS Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run test
  test-action:
    name: Test Action Run
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run action against test data
        uses: ./
        with:
          xcode-versions-file: ./src/__tests__/xcode-versions.yml
          xcode-search-path: ./src/__tests__/Xcodes

      - name: Validate run
        run: |
          if ! cmp --silent ./src/__tests__/workflows/input.yml ./src/__tests__/workflows/output.yml; then
            echo "Files do not match"
            echo "./src/__tests__/workflows/input.yml:"
            cat ./src/__tests__/workflows/input.yml
            echo "./src/__tests__/workflows/output.yml:"
            cat ./src/__tests__/workflows/output.yml
            exit 1
          fi
